name: 'gh-pages merge'
on: 
  push:
    branches:
      - main  

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: gh-pages Merge
      uses: robotology/gh-action-nightly-merge@v1.3.3
      with:
        stable_branch: 'main'
        development_branch: 'gh-pages'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
